<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-19 at 12:24:27.
 */
class AbstractCacheTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractCache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AbstractCache;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Onm\Cache\AbstractCache::setNamespace
     * @todo   Implement testSetNamespace().
     */
    public function testSetNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Onm\Cache\AbstractCache::fetch
     * @todo   Implement testFetch().
     */
    public function testFetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Onm\Cache\AbstractCache::contains
     * @todo   Implement testContains().
     */
    public function testContains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Onm\Cache\AbstractCache::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Onm\Cache\AbstractCache::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Onm\Cache\AbstractCache::deleteAll
     * @todo   Implement testDeleteAll().
     */
    public function testDeleteAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Onm\Cache\AbstractCache::deleteByRegex
     * @todo   Implement testDeleteByRegex().
     */
    public function testDeleteByRegex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Onm\Cache\AbstractCache::deleteByPrefix
     * @todo   Implement testDeleteByPrefix().
     */
    public function testDeleteByPrefix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Onm\Cache\AbstractCache::deleteBySuffix
     * @todo   Implement testDeleteBySuffix().
     */
    public function testDeleteBySuffix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
