<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-19 at 12:33:53.
 */
class ArrayCacheTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ArrayCache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArrayCache;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Onm\Cache\ArrayCache::getIds
     * @todo   Implement testGetIds().
     */
    public function testGetIds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
