<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-19 at 12:33:53.
 */
class MemcacheTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Memcache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Memcache;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Onm\Cache\Memcache::setMemcache
     * @todo   Implement testSetMemcache().
     */
    public function testSetMemcache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Onm\Cache\Memcache::getMemcache
     * @todo   Implement testGetMemcache().
     */
    public function testGetMemcache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Onm\Cache\Memcache::getIds
     * @todo   Implement testGetIds().
     */
    public function testGetIds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
